FROM node:latest as react-build
WORKDIR /app/client
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=react-build /app/client/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx","-g","daemon off;"]